# Generated by Django 2.2.7 on 2019-11-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191116_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='sender_email',
            field=models.EmailField(max_length=70),
        ),
    ]
